// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/kubernetes/typed/authentication/v1 (interfaces: AuthenticationV1Interface,TokenReviewInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/authentication/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v11 "k8s.io/client-go/kubernetes/typed/authentication/v1"
	rest "k8s.io/client-go/rest"
)

// MockAuthenticationV1Interface is a mock of AuthenticationV1Interface interface.
type MockAuthenticationV1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationV1InterfaceMockRecorder
}

// MockAuthenticationV1InterfaceMockRecorder is the mock recorder for MockAuthenticationV1Interface.
type MockAuthenticationV1InterfaceMockRecorder struct {
	mock *MockAuthenticationV1Interface
}

// NewMockAuthenticationV1Interface creates a new mock instance.
func NewMockAuthenticationV1Interface(ctrl *gomock.Controller) *MockAuthenticationV1Interface {
	mock := &MockAuthenticationV1Interface{ctrl: ctrl}
	mock.recorder = &MockAuthenticationV1InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationV1Interface) EXPECT() *MockAuthenticationV1InterfaceMockRecorder {
	return m.recorder
}

// RESTClient mocks base method.
func (m *MockAuthenticationV1Interface) RESTClient() rest.Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RESTClient")
	ret0, _ := ret[0].(rest.Interface)
	return ret0
}

// RESTClient indicates an expected call of RESTClient.
func (mr *MockAuthenticationV1InterfaceMockRecorder) RESTClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RESTClient", reflect.TypeOf((*MockAuthenticationV1Interface)(nil).RESTClient))
}

// SelfSubjectReviews mocks base method.
func (m *MockAuthenticationV1Interface) SelfSubjectReviews() v11.SelfSubjectReviewInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfSubjectReviews")
	ret0, _ := ret[0].(v11.SelfSubjectReviewInterface)
	return ret0
}

// SelfSubjectReviews indicates an expected call of SelfSubjectReviews.
func (mr *MockAuthenticationV1InterfaceMockRecorder) SelfSubjectReviews() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfSubjectReviews", reflect.TypeOf((*MockAuthenticationV1Interface)(nil).SelfSubjectReviews))
}

// TokenReviews mocks base method.
func (m *MockAuthenticationV1Interface) TokenReviews() v11.TokenReviewInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenReviews")
	ret0, _ := ret[0].(v11.TokenReviewInterface)
	return ret0
}

// TokenReviews indicates an expected call of TokenReviews.
func (mr *MockAuthenticationV1InterfaceMockRecorder) TokenReviews() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenReviews", reflect.TypeOf((*MockAuthenticationV1Interface)(nil).TokenReviews))
}

// MockTokenReviewInterface is a mock of TokenReviewInterface interface.
type MockTokenReviewInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenReviewInterfaceMockRecorder
}

// MockTokenReviewInterfaceMockRecorder is the mock recorder for MockTokenReviewInterface.
type MockTokenReviewInterfaceMockRecorder struct {
	mock *MockTokenReviewInterface
}

// NewMockTokenReviewInterface creates a new mock instance.
func NewMockTokenReviewInterface(ctrl *gomock.Controller) *MockTokenReviewInterface {
	mock := &MockTokenReviewInterface{ctrl: ctrl}
	mock.recorder = &MockTokenReviewInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenReviewInterface) EXPECT() *MockTokenReviewInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTokenReviewInterface) Create(arg0 context.Context, arg1 *v1.TokenReview, arg2 v10.CreateOptions) (*v1.TokenReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1.TokenReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTokenReviewInterfaceMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTokenReviewInterface)(nil).Create), arg0, arg1, arg2)
}
